In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]


In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
#this is vocubulary size
voc_size=10000

In [8]:
#Used to get Index from the dictionary
one_hot_repr=[one_hot(words,voc_size)for words in sent]
print(one_hot_repr)

[[3506, 7206, 8953, 3203], [3506, 7206, 8953, 6918], [3506, 2166, 8953, 2233], [5674, 4947, 5169, 1734, 6601], [5674, 4947, 5169, 1734, 654], [2123, 3506, 524, 8953, 134], [6508, 6925, 1278, 1734]]


In [10]:
from keras.layers import Embedding
from keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [11]:
import numpy as np

In [12]:
sent_len=8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedding_docs)

[[   0    0    0    0 3506 7206 8953 3203]
 [   0    0    0    0 3506 7206 8953 6918]
 [   0    0    0    0 3506 2166 8953 2233]
 [   0    0    0 5674 4947 5169 1734 6601]
 [   0    0    0 5674 4947 5169 1734  654]
 [   0    0    0 2123 3506  524 8953  134]
 [   0    0    0    0 6508 6925 1278 1734]]


In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_len))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedding_docs))

1/1 [==============================] - 0s 29ms/step
[[[ 1.3970956e-03 -4.5029629e-02  8.4954724e-03  4.4778708e-02
    1.3954233e-02 -3.4604587e-02  1.0209881e-02 -1.1362545e-03
    4.8252828e-03  4.1280638e-02]
  [ 1.3970956e-03 -4.5029629e-02  8.4954724e-03  4.4778708e-02
    1.3954233e-02 -3.4604587e-02  1.0209881e-02 -1.1362545e-03
    4.8252828e-03  4.1280638e-02]
  [ 1.3970956e-03 -4.5029629e-02  8.4954724e-03  4.4778708e-02
    1.3954233e-02 -3.4604587e-02  1.0209881e-02 -1.1362545e-03
    4.8252828e-03  4.1280638e-02]
  [ 1.3970956e-03 -4.5029629e-02  8.4954724e-03  4.4778708e-02
    1.3954233e-02 -3.4604587e-02  1.0209881e-02 -1.1362545e-03
    4.8252828e-03  4.1280638e-02]
  [-1.6658079e-02 -2.1391368e-02 -4.2752303e-02  8.9109167e-03
   -1.0477044e-02  4.6326030e-02  6.3577294e-03 -2.4334336e-02
   -2.8069330e-02 -3.1805277e-02]
  [-1.9444359e-02  2.4263550e-02 -3.0359162e-02  4.4734206e-02
    1.3860177e-02  1.9973863e-02  2.1626685e-02  1.7800476e-02
   -1.2210656e-02 -2.0

In [20]:
embedding_docs[0]

array([   0,    0,    0,    0, 3506, 7206, 8953, 3203])

In [21]:
print(model.predict(embedding_docs)[0])

1/1 [==============================] - 0s 30ms/step
[[ 0.0013971  -0.04502963  0.00849547  0.04477871  0.01395423 -0.03460459
   0.01020988 -0.00113625  0.00482528  0.04128064]
 [ 0.0013971  -0.04502963  0.00849547  0.04477871  0.01395423 -0.03460459
   0.01020988 -0.00113625  0.00482528  0.04128064]
 [ 0.0013971  -0.04502963  0.00849547  0.04477871  0.01395423 -0.03460459
   0.01020988 -0.00113625  0.00482528  0.04128064]
 [ 0.0013971  -0.04502963  0.00849547  0.04477871  0.01395423 -0.03460459
   0.01020988 -0.00113625  0.00482528  0.04128064]
 [-0.01665808 -0.02139137 -0.0427523   0.00891092 -0.01047704  0.04632603
   0.00635773 -0.02433434 -0.02806933 -0.03180528]
 [-0.01944436  0.02426355 -0.03035916  0.04473421  0.01386018  0.01997386
   0.02162668  0.01780048 -0.01221066 -0.02065996]
 [ 0.03285036  0.01424017  0.04749693  0.04680033  0.02768702  0.03356451
   0.04829252 -0.02043859 -0.03104367  0.00797836]
 [-0.02555106 -0.0099906   0.00440546  0.01855541 -0.01075144 -0.03751652